### PR TITLE
eslint-plugin-project-structure

### PR DESCRIPTION
**Pull request by Igorkowalski94**
## project‑structure/​folder‑structure
Checks the correctness of file and folder naming as well as the entire structure of a given folder.
For example, the `hooks` folder can only contain files that must follow the pattern `use-{kebab-case}.ts`, and folders are not allowed within it (Flat structure). It also validates file extensions, including those not supported by ESLint, such as `.json` and `.sql`.

I based the structure on the current files and folders. If you want to change or add anything, I'd be happy to help and explain everything.

[project‑structure/folder-structure documentation](https://github.com/Igorkowalski94/eslint-plugin-project-structure/wiki/project%E2%80%91structure-%E2%80%8Bfolder%E2%80%91structure#root)

## project‑structure/independent-modules
Is an alternative to eslint-plugin-boundaries. 

It supports ESLint version 9+, which is not supported by eslint-plugin-boundaries. It also has a simpler API and offers more flexibility in creating more detailed rules, especially for nested folder structures.

I added all the rules you described in the video, including an additional rule for `permissions.ts` file.

[project‑structure/independent-modules documentation
](https://github.com/Igorkowalski94/eslint-plugin-project-structure/wiki/project%E2%80%91structure-%E2%80%8Bindependent%E2%80%91modules#root)

I also recommend [project‑structure/file-composition](https://github.com/Igorkowalski94/eslint-plugin-project-structure/wiki/project%E2%80%91structure-%E2%80%8Bfile%E2%80%91composition#root), which allows you to:
- Enforce that the exported component has the same name as the file name.
- Prohibit the use of certain selectors in a given file.
- Enforce the order of selectors for example, the interface with the component's props will always be first, the main component second, the component styles third, and so on.
- Enforce that there is a maximum of one component per file, and its subcomponents should be in a separate file/folder.

### CODE REVIEW

**Comment by WebDevSimplified** [comment]
Is the `folderStructure.jsonc` file actually needed to get the same functionality? It seems this adds even more rules on top of the shared/feature/app split I defined. It also seems too strict since every time you need a new folder (for example in one of the feature/components folders) you need to modify the config which is not something I would want to do.

**Comment by Igorkowalski94** [comment]
All the functionality you described in the video is contained in independentModules.jsonc, which checks the correctness of imports. folderStructure.jsonc is an addition, it checks the correctness of file and folder naming as well as their structure, something that eslint-plugin-boundaries does not do.

**Comment by Igorkowalski94** [comment]
Could you provide an example of what the structure of the feature folder should look like? I was following what was already in the repository, so I assumed that in feature/components you only want to have subfolders like charts and forms. It's possible to set a dynamic name like {camelCase}, so you wouldn't need to configure anything.

**Comment by Igorkowalski94** [comment]
If you're not interested in additionally checking the correctness of file and folder naming, as well as the structure of the folders, I can remove folderStructure.jsonc.

**Comment by WebDevSimplified** [comment]
To be honest there is no structure for the files/folders beyond what I described in this video. I mostly wanted the video to showcase how a one way data flow can be used in general across all projects (not just this specific project). This is why I put no requirements on folder names (other than the feature and app folder) or file structure in those folder.

**Comment by Igorkowalski94** [comment]
Ready for review. 

I removed the entire folder-structure configuration.
I also added custom error messages that point to the source of the problem and explain the data flow from your video.
You can test it out and see if everything works as expected. Let me know if you have any questions or if you want to add any additional rules.

**Comment by Igorkowalski94** [comment]
Done

**Comment by WebDevSimplified** [comment]
This looks great! One minor change, though. Can you change the link to the video to have the text say `Video explanation of this folder structure`. Once that is done I will merge it in.

**Pull request merged**
